# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/bryan/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-22228-ZHUB-POWERSPEC/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.cache/wt [current_project]
set_property parent.project_path D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_output_repo d:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/git/final-proj-bzz3/charLib.coe
read_vhdl -library xil_defaultlib {
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/imports/final-proj-bzz3/clock_div.vhd
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/new/doubledabble.vhd
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/new/doubledabblerev.vhd
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/new/gcd.vhd
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/new/gcd_div.vhd
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/new/receiver.vhd
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/new/transmitter.vhd
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/imports/final-proj-bzz3/uart.vhd
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/imports/final-proj-bzz3/uart_rx.vhd
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/imports/final-proj-bzz3/uart_tx.vhd
  D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/sources_1/new/bzz3top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/constrs_1/imports/final-proj-bzz3/Z7_7010_7020.xdc
set_property used_in_implementation false [get_files D:/git/final-proj-bzz3/bzz3finalproj/bzz3finalproj.srcs/constrs_1/imports/final-proj-bzz3/Z7_7010_7020.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top bzz3top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bzz3top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bzz3top_utilization_synth.rpt -pb bzz3top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
